export const QUERY_KEYS = {
  VEHICLES: "VEHICLES",
  VEHICLE_TYPES: "VEHICLE_TYPES",
  RESERVATION: "RESERVATION",
  COST_RESERVATION: "COST_RESERVATION",
  CUSTOMER: "CUSTOMER",
  CHECK_PARAMETER: "CHECK_PARAMETER",
  MAINTENANCE: "MAINTENANCE",
};
